# Generated by Django 4.2 on 2024-05-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdSK4rIxxlnivgL0poO3Rc1NLF2P1A_iTtbmRS6TWKQQ&s', max_length=500),
        ),
    ]
